export const QueryKeys = {
  // AUTH QUERY
  LOGIN: "LOGIN",

  // USERS QUERY
  USERS:"USERS",
  USER: "USER",

  // TASK QUERY
  TASKS: "TASKS",
  TASK: "TASK",

  // SUB TASK QUERY
  SUBTASKS: "SUBTASKS",
  SUBTASK: "SUBTASK",

  // MODULES QUERY
  MODULES: "MODULES",
  MODULE: "MODULE",

  // CLIENTS QUERY
  CLIENTS: "CLIENTS",
  CLIENT: "CLIENT"
};
