export const QueryKeys = {
  // AUTH QUERY
  LOGIN: "LOGIN",

  // LANDING BANNER
  LANDING_BANNERS: "LANDING_BANNERS",

  // LANDING GENRE
  LANDING_GENRES: "LANDING_GENRES",

  // LANDING NEW AGE LIBRARY
  LANDING_NEW_AGE_LIBRARY: "LANDING_NEW_AGE_LIBRARY",
};
